theme = "solarized_dark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
#popup-border = "all"
scrolloff = 3
# true-color = true

[editor.auto-pairs]
"\"" = "\""
"'" = "'"
"(" = ")"
#"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"A-," = "jump_backward"
"A-." = "goto_definition"
"A->" = "jump_forward"
"A-m" = "remove_primary_selection"
