theme = "solarized_dark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
#popup-border = "all"
scrolloff = 3
# true-color = true

[editor.auto-pairs]
"\"" = "\""
"'" = "'"
"(" = ")"
#"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "register"]
right = ["version-control", "diagnostics", "selections", "register", "position", "file-encoding"]

[keys.normal]
"A-," = "jump_backward"
"A-." = "goto_definition"
"A->" = "jump_forward"
"A-m" = "remove_primary_selection"
